import type { AssetProfile } from "./assets.js";
import type { ComplianceFrictionResult } from "./compliance-friction.js";
import type {
  DistributionHealthResult,
  MantleEcosystemMetrics,
  MarketMetrics,
} from "./metrics.js";

export interface DistributionReport {
  asset: AssetProfile;
  generatedAt: string;
  distributionHealth: DistributionHealthResult;
  complianceFriction: ComplianceFrictionResult;
  market: MarketMetrics | null;
  ecosystem: MantleEcosystemMetrics;
  bottlenecks: string[];
  mantleLevers: string[];
  nextSteps: string[];
}

export function buildReport(input: {
  asset: AssetProfile;
  distributionHealth: DistributionHealthResult;
  complianceFriction: ComplianceFrictionResult;
  market: MarketMetrics | null;
  ecosystem: MantleEcosystemMetrics;
}): DistributionReport {
  const bottlenecks: string[] = [];

  if (input.complianceFriction.score >= 7) {
    bottlenecks.push(
      `Compliance friction (${input.complianceFriction.score}/10) — ${input.complianceFriction.label}: accreditation and jurisdiction gates limit global buyer pool`,
    );
  } else {
    bottlenecks.push(
      `Compliance friction (${input.complianceFriction.score}/10) — venue KYC and regional rules still slow onboarding`,
    );
  }

  if (input.distributionHealth.score < 6) {
    bottlenecks.push(
      `Distribution health (${input.distributionHealth.score}/10) — liquidity and venue depth need strengthening`,
    );
  }

  const venue = input.distributionHealth.components.find((c) => c.name === "venue_depth");
  if (venue && venue.score < 5) {
    bottlenecks.push("Fluxion / DEX venue depth is thin relative to issuance narrative");
  }

  bottlenecks.push(
    "Fiat on-ramp and broker-dealer alignment remain off-chain distribution dependencies",
  );

  const mantleLevers = [
    "xStocks + Fluxion + Bybit stack — consolidate discovery and execution in one Mantle-native flow",
    "InsightX prediction markets — use demand signals to prioritize which RWAs to market",
    "Mantle AI Agent Skills — automate compliance pre-checks before routing capital (see Compliance Gate pattern)",
    `Aave on Mantle ($${Math.round(input.ecosystem.aaveMantleTvlUsd).toLocaleString()} TVL) — composable yield rails for institutions already on-chain`,
  ];

  const nextSteps = [
    "Publish holder concentration dashboard (Dune) to validate liquidity vs issuance claims",
    "Pair tokenized equity listings with jurisdiction-specific onboarding playbooks",
    "Incentivize market makers on Fluxion for top xStocks pairs",
    "Deploy agent-callable compliance gate before agent-initiated RWA transfers",
  ];

  return {
    asset: input.asset,
    generatedAt: new Date().toISOString(),
    distributionHealth: input.distributionHealth,
    complianceFriction: input.complianceFriction,
    market: input.market,
    ecosystem: input.ecosystem,
    bottlenecks: bottlenecks.slice(0, 4),
    mantleLevers,
    nextSteps,
  };
}

export function renderMarkdown(report: DistributionReport): string {
  const { asset, distributionHealth, complianceFriction, market, ecosystem } = report;

  const marketBlock = market
    ? `| Metric | Value |
| --- | --- |
| Market cap | $${market.marketCapUsd?.toLocaleString() ?? "n/a"} |
| 24h volume | $${market.volume24hUsd?.toLocaleString() ?? "n/a"} |
| FDV | $${market.fdvUsd?.toLocaleString() ?? "n/a"} |
| Vol / MCap | ${market.volumeToMcap != null ? `${(market.volumeToMcap * 100).toFixed(1)}%` : "n/a"} |
| 24h change | ${market.priceChange24hPct?.toFixed(2) ?? "n/a"}% |`
    : "_Live market data unavailable — scores use ecosystem metrics only._";

  return `# Distribution Friction Report: ${asset.symbol}

> Generated by Mantle Distribution Friction Agent · ${report.generatedAt}
> Built for Mantle Research Challenge — Track 2

## Executive Summary

**${asset.name}** on Mantle via **${asset.distributionChannel}**.

| Score | Value | Meaning |
| --- | --- | --- |
| **Distribution Health** | **${distributionHealth.score}/10** (${distributionHealth.label}) | Higher = capital is moving; liquidity + venue depth |
| **Compliance Friction** | **${complianceFriction.score}/10** (${complianceFriction.label}) | Higher = harder to reach global buyers |

**Thesis:** Issuance is solved. Distribution fails at **compliance + venue + discovery** — not at token minting.

---

## Key Metrics

### Asset market (${market?.source ?? "n/a"})

${marketBlock}

### Mantle ecosystem (${ecosystem.source})

| Metric | Value |
| --- | --- |
| Chain TVL | $${Math.round(ecosystem.chainTvlUsd).toLocaleString()} |
| RWA TVL (est.) | $${Math.round(ecosystem.rwaTvlUsd).toLocaleString()} |
| Fluxion TVL | $${Math.round(ecosystem.fluxionTvlUsd).toLocaleString()} |
| Aave Mantle | $${Math.round(ecosystem.aaveMantleTvlUsd).toLocaleString()} |
| Ondo Mantle | $${Math.round(ecosystem.ondoMantleTvlUsd).toLocaleString()} |

---

## Distribution Health Breakdown

${distributionHealth.components
  .map(
    (c) =>
      `- **${c.name}** (${c.score}/10, weight ${(c.weight * 100).toFixed(0)}%): ${c.detail}`,
  )
  .join("\n")}

---

## Compliance Friction Breakdown

${complianceFriction.gateChecks
  .map((c) => `- **${c.name}** (+${c.friction}): ${c.detail}`)
  .join("\n")}

**Drivers:**
${complianceFriction.drivers.map((d) => `- ${d}`).join("\n")}

---

## Main Bottlenecks

${report.bottlenecks.map((b, i) => `${i + 1}. ${b}`).join("\n")}

---

## Mantle Leverage Opportunities

${report.mantleLevers.map((l) => `- ${l}`).join("\n")}

---

## Actionable Next Steps (90 days)

${report.nextSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

---

_Built as part of Mantle Research Challenge Track 2 · [@Mistakili](https://github.com/Mistakili)_
`;
}